### ISSUE TITLE
Lead Administrators unable to set player's rank above Rank 15

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#116]
Lead administrators are not able to set a player's rank above 15. When they use "/set", it will say "Invalid value! (No Such Rank Number".

**Comment by TommyB123** [comment]
fixed on current build

**Comment by reemyrobby** [comment]
Issue is still present (even in the development server), so I am going to assume this is still not fixed.

**Comment by TommyB123** [comment]
awkward
